/**
 * Registers (or removes) a Windows Scheduled Task that runs the daily batch.
 *
 *   node src/schedule.mjs install [--time 07:00]
 *   node src/schedule.mjs status
 *   node src/schedule.mjs remove
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { ROOT } from './store.mjs';

const TASK_NAME = 'MicrosoftHiringSignal';
const RUNNER = path.join(ROOT, 'scripts', 'run-daily.cmd');
const LOG = path.join(ROOT, 'data', 'batch.log');

function ps(script) {
  return execFileSync(
    'powershell.exe',
    ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-Command', script],
    { encoding: 'utf8' }
  );
}

/**
 * A .cmd wrapper keeps quoting sane and gives the task a stable, loggable entry
 * point that can also be run by hand.
 *
 * @param {boolean} publish also commit and push docs/ after a successful batch
 */
function writeRunner(publish) {
  fs.mkdirSync(path.dirname(RUNNER), { recursive: true });
  fs.mkdirSync(path.dirname(LOG), { recursive: true });

  const lines = [
    '@echo off',
    'rem Generated by src/schedule.mjs - runs the daily Microsoft careers batch.',
    `cd /d "${ROOT}"`,
    `echo. >> "${LOG}"`,
    `echo ===== %DATE% %TIME% ===== >> "${LOG}"`,
    `"${process.execPath}" "${path.join(ROOT, 'src', 'daily.mjs')}" >> "${LOG}" 2>&1`,
    'if errorlevel 1 exit /b %ERRORLEVEL%',
  ];

  if (publish) {
    lines.push(
      'rem Publish the refreshed site. Nothing to commit is not an error.',
      `git add docs >> "${LOG}" 2>&1`,
      `git diff --cached --quiet && (echo No data change to publish. >> "${LOG}") || (`,
      `  git commit -m "data: daily batch %DATE%" >> "${LOG}" 2>&1`,
      `  git push origin main >> "${LOG}" 2>&1`,
      ')'
    );
  }

  lines.push('exit /b 0', '');
  fs.writeFileSync(RUNNER, lines.join('\r\n'));
  return RUNNER;
}

function install(time, publish) {
  writeRunner(publish);
  const script = `
$ErrorActionPreference = 'Stop'
$action    = New-ScheduledTaskAction -Execute '${RUNNER}'
$trigger   = New-ScheduledTaskTrigger -Daily -At '${time}'
$settings  = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries \`
             -DontStopIfGoingOnBatteries -ExecutionTimeLimit (New-TimeSpan -Hours 4) \`
             -MultipleInstances IgnoreNew
Register-ScheduledTask -TaskName '${TASK_NAME}' -Action $action -Trigger $trigger \`
  -Settings $settings -Description 'Daily crawl of careers.microsoft.com for the Hiring Signal dashboard.' -Force | Out-Null
Write-Output 'registered'
`;
  ps(script);
  console.log(`Scheduled task "${TASK_NAME}" installed \u2014 runs daily at ${time}.`);
  console.log(`  runner:  ${RUNNER}`);
  console.log(`  log:     ${LOG}`);
  console.log(`  publish: ${publish ? 'yes \u2014 commits and pushes docs/ after each batch' : 'no (pass --publish to enable)'}`);
}

function remove() {
  ps(`Unregister-ScheduledTask -TaskName '${TASK_NAME}' -Confirm:$false; Write-Output 'removed'`);
  console.log(`Scheduled task "${TASK_NAME}" removed.`);
}

function status() {
  const out = ps(
    `$t = Get-ScheduledTask -TaskName '${TASK_NAME}' -ErrorAction SilentlyContinue
     if (-not $t) { Write-Output 'NOT INSTALLED'; exit 0 }
     $i = Get-ScheduledTaskInfo -TaskName '${TASK_NAME}'
     Write-Output ("State:      " + $t.State)
     Write-Output ("Last run:   " + $i.LastRunTime)
     Write-Output ("Last result:" + $i.LastTaskResult)
     Write-Output ("Next run:   " + $i.NextRunTime)`
  );
  console.log(out.trim());
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const cmd = process.argv[2] || 'status';
  const timeIdx = process.argv.indexOf('--time');
  const time = timeIdx > -1 ? process.argv[timeIdx + 1] : '07:00';
  const publish = process.argv.includes('--publish');
  try {
    if (cmd === 'install') install(time, publish);
    else if (cmd === 'remove') remove();
    else status();
  } catch (err) {
    console.error('Scheduler command failed:', err.message);
    console.error('Registering a scheduled task may require an elevated terminal.');
    process.exit(1);
  }
}
